//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocoEx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PocoEx.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Use &apos;throw;&apos;. &apos;throw ex;&apos; resets the stacktrace. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00001Description {
            get {
                return ResourceManager.GetString("PocoEx00001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use &apos;throw;&apos; to rethrow &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00001MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Throws the catching exception explicitly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00001Title {
            get {
                return ResourceManager.GetString("PocoEx00001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rethrow the wrapper exception with the cause. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00002Description {
            get {
                return ResourceManager.GetString("PocoEx00002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize &apos;{0}&apos; with the inner exception(&apos;{1}&apos;). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00002MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The wrapper exception ignores the cause. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00002Title {
            get {
                return ResourceManager.GetString("PocoEx00002Title", resourceCulture);
            }
        }
    }
}
