//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocoEx.CodeAnalysis {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PocoEx.CodeAnalysis.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Use &apos;throw;&apos; to rethrow &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00001MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The stacktrace is reset. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00001Title {
            get {
                return ResourceManager.GetString("PocoEx00001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize &apos;{0}&apos; with the inner exception(&apos;{1}&apos;). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00002MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The wrapper exception ignores the cause. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00002Title {
            get {
                return ResourceManager.GetString("PocoEx00002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Equals(object)&apos; should be overridden. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00101MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00101MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Equals(object)&apos; is not overridden. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00101Title {
            get {
                return ResourceManager.GetString("PocoEx00101Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; should implement &apos;IEquatable&lt;{0}&gt;&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00102MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00102MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A structure type doesn&apos;t implement &apos;IEquatable&lt;T&gt;&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00102Title {
            get {
                return ResourceManager.GetString("PocoEx00102Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Equals(object)&apos; should invoke {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00103MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00103MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Equals(object)&apos; don&apos;t invoke any of &apos;Equals(T)&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00103Title {
            get {
                return ResourceManager.GetString("PocoEx00103Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;ReferenceEquals({0}, null)&apos; should be invoked to check for null reference. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00104MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00104MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter is a reference type object, but is not checked for null reference. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00104Title {
            get {
                return ResourceManager.GetString("PocoEx00104Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;ReferenceEquals({0}, this)&apos; should be invoked to check for reference equality. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00105MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00105MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameter is a reference type object, but is not checked for reference equality. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00105Title {
            get {
                return ResourceManager.GetString("PocoEx00105Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Equals({0})&apos; should check for the equality of &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00106MessageFormat {
            get {
                return ResourceManager.GetString("PocoEx00106MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check all public instance fields or properties of the parameter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PocoEx00106Title {
            get {
                return ResourceManager.GetString("PocoEx00106Title", resourceCulture);
            }
        }
    }
}
